<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-24 at 21:04:47.
 */
class YAPFLoggerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var YAPFLogger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new YAPFLogger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers YAPFLogger::log
     * @todo   Implement testLog().
     */
    public function testLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
