<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-23 at 19:36:12.
 */

require_once __DIR__ . '/../../../core/PDODB.php';

class PDODBTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PDODB
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PDODB::queryOne
     * @todo   Implement testQueryOne().
     */
    public function testQueryOne() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
